name: vive_la_uca
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter_native_splash: ^2.4.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_map: ^7.0.1
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
 


flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/logo.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat.ttf
          weight: 800 # Fixed indentation and weight

