name: vive_la_uca
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter_native_splash: ^2.4.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
 


flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/logo.png
    - lib/assets/images/CMR.png
    - lib/assets/images/M7.jpg
  fonts:

    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat.ttf
          weight: 800 # Fixed indentation and weight

    - family: MontserratBold
      fonts:
        - asset: lib/assets/fonts/Montserrat-Bold.ttf
          weight: 800 # Fixed indentation and weight
    

