name: vive_la_uca
description: 'A new Flutter project.'

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_map_location_marker: ^8.0.0
  flutter_native_splash: ^2.4.0
  flutter_polyline_points: ^2.0.0
  geolocator: ^11.0.0
  go_router: ^5.0.0
  http: ^1.2.1
  latlong2: ^0.9.1
  permission_handler: ^11.3.1
  restart_app: ^1.2.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/logo.png
    - lib/assets/images/owlIcon.png
    - lib/assets/images/pinlocation.png
    - lib/assets/images/CMR.png
    - lib/assets/images/M7.jpg
  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat.ttf
          weight: 800 # Fixed indentation and weight

    - family: MontserratBold
      fonts:
        - asset: lib/assets/fonts/Montserrat-Bold.ttf
          weight: 800 # Fixed indentation and weight
